// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2xwDt_AiXCblYaxeY2jYPIRsX3g5eomg',
    appId: '1:821778987621:web:55c2e9521864f61b55648c',
    messagingSenderId: '821778987621',
    projectId: 'sixtattoo-898c0',
    authDomain: 'sixtattoo-898c0.firebaseapp.com',
    databaseURL: 'https://sixtattoo-898c0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sixtattoo-898c0.appspot.com',
    measurementId: 'G-494FLBSKBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCABDwyEHIvL0xuwRJVn0425ZsIqyHaVzA',
    appId: '1:821778987621:android:fc7d5af31df75b5455648c',
    messagingSenderId: '821778987621',
    projectId: 'sixtattoo-898c0',
    databaseURL: 'https://sixtattoo-898c0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sixtattoo-898c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQRXQLU7v4zIwvKeDzAC82bXvxp19f6sQ',
    appId: '1:821778987621:ios:433d0907537d78b555648c',
    messagingSenderId: '821778987621',
    projectId: 'sixtattoo-898c0',
    databaseURL: 'https://sixtattoo-898c0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sixtattoo-898c0.appspot.com',
    androidClientId: '821778987621-45do4l83vcphfeud5fkel2oh5pqip9ct.apps.googleusercontent.com',
    iosClientId: '821778987621-60r0ppst5l3rkh058dtij2bq4mqar870.apps.googleusercontent.com',
    iosBundleId: 'com.example.sixxTattoo',
  );
}
